controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1     
      - joint_2        
      - joint_3     
      - joint_4              
      - joint_5     
      - joint_6      
      - joint_7     
      - joint_8        
      - joint_9     
      - joint_10              
      - joint_11     
      - joint_12     
